@extends('layouts.app')
@section('title', $settings['default_title'] ?? 'AI Shop - فروشگاه دیجیتال')
@section('meta_description', $settings['meta_description'] ?? 'خرید آنلاین محصولات دیجیتال')
@section('content')
<section class="hero-banner"><div class="container"><div class="hero-slider" data-slider>@forelse($sliders as $slide)<div class="hero-content slide {{ $loop->first?'active':'' }}"><div><span class="hero-badge">فروش ویژه محصولات دیجیتال</span><h1>{{ $slide->title }}</h1><p>{{ $slide->subtitle }}</p><a class="btn-hero" href="{{ $slide->button_link ?: route('products.index') }}">{{ $slide->button_text ?: 'مشاهده محصولات' }}</a></div><div class="hero-card"><img src="{{ \App\Support\ShopImage::url($slide->image, 'banner') }}" alt="{{ $slide->title }}"><strong>پیشنهاد ویژه امروز</strong></div></div>@empty<div class="hero-content active"><div><span class="hero-badge">فروش ویژه محصولات دیجیتال</span><h1>خرید آسان، سریع و هوشمند</h1><p>جدیدترین موبایل‌ها، لپ‌تاپ‌ها و لوازم دیجیتال را با قیمت مناسب تهیه کنید.</p><a class="btn-hero" href="{{ route('products.index') }}">مشاهده محصولات</a></div><div class="hero-card"><h3>پیشنهاد امروز</h3><p>هدفون بی‌سیم حرفه‌ای</p><strong>فقط ۱,۲۰۰,۰۰۰ تومان</strong></div></div>@endforelse<button class="slider-btn prev" type="button">‹</button><button class="slider-btn next" type="button">›</button></div></div></section>
<section class="categories-section" id="categories"><div class="container"><div class="section-head"><h2 class="section-title">{{ $sections['categories']->title ?? 'دسته‌بندی‌های محبوب' }}</h2><a href="{{ route('categories.index') }}">مشاهده همه</a></div><div class="category-list">@foreach($categories as $category)<a class="category-item" href="{{ route('categories.show',$category->slug) }}"><img src="{{ \App\Support\ShopImage::url($category->image, 'category') }}" alt="{{ $category->name }}"><p>{{ $category->name }}</p><small>{{ $category->description }}</small></a>@endforeach</div></div></section>
<section class="amazing-section" id="products"><div class="container"><div class="amazing-box"><div class="amazing-title"><h2>{{ $sections['featured_products']->title ?? 'پیشنهادهای شگفت‌انگیز' }}</h2><p>{{ $sections['featured_products']->subtitle ?? 'محصولات منتخب با تخفیف ویژه' }}</p></div><div class="row g-3">@foreach($featuredProducts as $product)<div class="col-12 col-sm-6 col-lg-3">@include('partials.product-card',['product'=>$product])</div>@endforeach</div></div></div></section>
<section class="products-section"><div class="container"><div class="section-head"><h2 class="section-title">{{ $sections['best_sellers']->title ?? 'پرفروش‌ترین محصولات' }}</h2><a href="{{ route('products.index',['sort'=>'popular']) }}">مشاهده همه</a></div><div class="row g-4">@foreach($bestSellers as $product)<div class="col-12 col-sm-6 col-lg-3">@include('partials.product-card',['product'=>$product])</div>@endforeach</div></div></section>
<section class="products-section"><div class="container"><div class="section-head"><h2 class="section-title">{{ $sections['latest_products']->title ?? 'جدیدترین محصولات' }}</h2><a href="{{ route('products.index') }}">فروشگاه</a></div><div class="row g-4">@foreach($latestProducts as $product)<div class="col-12 col-sm-6 col-lg-3">@include('partials.product-card',['product'=>$product])</div>@endforeach</div></div></section>
<section class="trust-section"><div class="container"><div class="trust-grid">@foreach(['ارسال سریع','ضمانت اصالت کالا','پرداخت امن','پشتیبانی ۲۴/۷','بازگشت کالا'] as $item)<div>✅<strong>{{ $item }}</strong></div>@endforeach</div></div></section>
<section class="products-section"><div class="container"><h2 class="section-title">برندها و تأمین‌کنندگان</h2><div class="brand-row">@foreach($brands as $brand)<span><img src="{{ \App\Support\ShopImage::url($brand->logo, 'brand') }}" alt="{{ $brand->name }}"><strong>{{ $brand->name }}</strong></span>@endforeach</div></div></section>
<section class="products-section testimonials"><div class="container"><h2 class="section-title">نظر مشتریان</h2><div class="row g-4"><div class="col-md-4"><div class="simple-card">خرید سریع و بسته‌بندی عالی بود.</div></div><div class="col-md-4"><div class="simple-card">تنوع محصولات دیجیتال خیلی خوب است.</div></div><div class="col-md-4"><div class="simple-card">پشتیبانی باحوصله و حرفه‌ای.</div></div></div></div></section>
<section class="products-section"><div class="container"><div class="section-head"><h2 class="section-title">مجله فروشگاه</h2><a href="{{ route('blog.index') }}">همه مقالات</a></div><div class="row g-4">@foreach($articles as $article)<div class="col-md-4"><a class="simple-card article-card" href="{{ route('blog.show',$article->slug) }}"><img src="{{ \App\Support\ShopImage::url($article->image, 'article') }}" alt="{{ $article->title }}"><h3>{{ $article->title }}</h3><p>{{ $article->excerpt }}</p></a></div>@endforeach</div></div></section>
@endsection
